# Generated by Django 5.1.4 on 2025-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0009_alter_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_current_address',
            field=models.BooleanField(default=False),
        ),
    ]
