# Generated by Django 5.1.4 on 2025-05-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0010_shippingaddress_is_current_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobiles', 'mobiles'), ('laptops', 'laptops'), ('clothing', 'clothing')], default='mobiles', max_length=10),
        ),
    ]
